name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Check required files
        run: |
          REQUIRED_FILES=(
            "docker-compose.yml"
            "config/postgres/init.sql"
            "config/traefik/dynamic/auth.yml"
          )
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -e "$file" ]; then
              echo "Missing required file: $file"
              exit 1
            fi
          done

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/github_deploy_key
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Run
        run: |
          ssh -i ~/.ssh/github_deploy_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            PROJECT_DIR="/root/app"
            REPO_URL="git@github.com:FacturaSV/arch-fe.git"

            # Crear ruta si no existe
            if [ ! -d "$PROJECT_DIR" ]; then
              mkdir -p "$PROJECT_DIR"
              git clone "$REPO_URL" "$PROJECT_DIR"
            fi

            cd "$PROJECT_DIR"

            # Verificar archivos requeridos
            REQUIRED_FILES=("docker-compose.yml" "config/postgres/init.sql" "config/traefik/dynamic/auth.yml")
            for file in "${REQUIRED_FILES[@]}"; do
              if [ ! -e "$file" ]; then
                echo "Falta el archivo requerido: $file"
                exit 1
              fi
            done

            git pull origin main
            docker compose pull
            docker compose up -d --build
          EOF